baseURL: http://example.org/
languageCode: en-us
title: Symposium 2023

theme: PaperMod

menu:
  main:
    - identifier: program
      name: PROGRAM
      url: /
      weight: 10
    - identifier: organizers
      name: ORGANIZERS
      url: /
      weight: 20
    - identifier: participants
      name: PARTICIPANTS
      url: /
      weight: 30

params:
  label:
    text: "HOME"
    icon: logo/100th bosscha black.png
    iconHeight: 35


