baseURL: http://example.org/
languageCode: en-us
title: My New Hugo Site

theme: PaperMod

menu:
  main:
    - identifier: program
      name: Program
      url: /
      weight: 10
    - identifier: organizers
      name: Organizers
      url: /
      weight: 20
    - identifier: participants
      name: Participants
      url: /
      weight: 30

params:
  label:
    text: " "
    icon: logo/logo-OB-color.svg
    iconHeight: 35


